---
title: "Explore Stanfit"
output: html_document
runtime: shiny
---
```{r, include=F}
knitr::opts_chunk$set(echo = F)
```

```{r}
betas <- ahnold_fit_stan %>% 
  as.data.frame() %>% 
  select(contains('betas')) %>% 
  as_data_frame() 

beta_groups <- str_replace_all(colnames(betas),'\\d|\\[|\\]','')

group_names <- unique(str_replace_all(colnames(betas),'\\d|\\[|\\]',''))

for (i in group_names){
  
  
  variable_name <- paste0("x_",str_replace_all(i,'_betas',''))
  
  seen_var <- ifelse(str_detect(variable_name,'seen'),'_seen','_seeing')
  
  colnames(betas)[str_detect(colnames(betas), i)] <-   paste0(colnames(eval(rlang::parse_expr(variable_name))),seen_var)
  
  
}

cs_betas <- purrrlyr::dmap(betas, center_scale) %>% 
  mutate(iteration = 1:nrow(.)) %>% 
  gather(variable,estimate,-iteration) %>% 
  nest(-variable)
```

```{r}
diagnose_mcmc <- function(data,name){
  
  trace_plot <- data %>% 
    ggplot(aes(iteration, estimate)) + 
    geom_line() + 
    labs(title = name)
  
  ac_plot <- data_frame(ACF = acf(data$estimate, plot = F)$acf %>% drop()) %>% 
    mutate(lag = 1:nrow(.)- 1) %>% 
    ggplot(aes(lag, ACF)) + 
    geom_col()
  
  trace_plot + ac_plot + plot_layout(ncol = 1, nrow = 2)
  

}

cs_betas <- cs_betas %>% 
  mutate(stan_plot = map2_plot(data, variable, diagnose_mcmc))

trelliscopejs::trelliscope(cs_betas, name = 'diagnose_stan', panel_col = 'stan_plot')


```


```{r}
did_betas <- betas[, str_detect(beta_groups,'did')] %>% 
  gather(variable, value) %>% 
  separate(variable,c('year','type'),sep = '_') %>% 
  mutate(year = as.numeric(year))

did_betas %>% 
ggplot(aes(year, value, group = factor(year))) + 
  geom_violin() + 
  facet_wrap(~type)
```

Seems close,

```{r}


a = summary(ahnold_fit_stan)$summary

```




