---
title: "Explore Stanfit"
output: html_document
runtime: shiny
---
```{r, include=F}
knitr::opts_chunk$set(echo = F)
```

```{r, echo = F}
library(tidyverse)
library(rstan)
library(shiny)
load(here::here('cluster-seen-only.Rdata'))
load(here::here('x_seen.Rdata'))


year_betas <- ahnold_stan_fit %>% 
  as.data.frame() %>% 
  select(contains('betas')) %>% 
  as_data_frame() %>% 
  set_names(colnames(x_seen)) %>% 
  select(contains('20')) %>% 
  mutate(iteration = 1:nrow(.)) %>% 
  gather(classcode_year, beta_hat,-iteration) %>% 
  tidyr::separate(classcode_year,c('classcode','year'),'-') %>% 
  mutate(year = as.numeric(year)) %>% 
  group_by(classcode,year) %>% 
  mutate(cs_beta_hat = (beta_hat - mean(beta_hat)) / (2 * sd(beta_hat))) %>% ungroup() %>% 
  group_by(classcode, year) %>% 
  ungroup()


```



Choose species
```{r}

selectInput(
      'species',
      'Species to Plot' ,
      choices = unique(year_betas$classcode),
      multiple = T,
      selectize = T
    )

```

Choose years

```{r}

selectInput(
      'years',
      'Years to plot' ,
      choices = unique(year_betas$year),
      multiple = T,
      selectize = T
    )



```

plot year effects

```{r}

renderPlot({
  
  out <- year_betas %>% 
    filter(classcode %in% input$species,
           year %in% input$years) %>% 
    ggplot(aes(iteration, cs_beta_hat, color = factor(year))) + 
    geom_line(alpha = 0.5) +
  facet_wrap(~classcode) +
  theme_classic() + 
  viridis::scale_color_viridis(discrete = T)
  
  out
  
})

```

plot year autocorrelations

```{r}


renderPlot({
  
year_betas %>% 
    filter(classcode %in% input$species,
           year %in% input$years) %>%
    group_by(classcode, year) %>% 
    summarise(lag_acf = list(acf(beta_hat, plot = F, lag.max = 10)$acf %>% drop())) %>% 
    mutate(lag_acf = map(lag_acf, ~data_frame(lag = 1:length(.x), ac = .x))) %>% 
    unnest() %>% 
    ungroup() %>% 
    mutate(year = as.factor(year),
           lag = as.numeric(lag)) %>% 
    ggplot(aes(lag, ac, color = factor(year))) + 
        geom_hline(aes(yintercept = 0)) +
    geom_line(alpha = 0.5) +
  facet_wrap(~classcode) +
  theme_classic() + 
  viridis::scale_color_viridis(discrete = T)  
})

```


Choose regions

```{r}

region_betas <- ahnold_stan_fit %>% 
  as.data.frame() %>% 
  select(contains('betas')) %>% 
  as_data_frame() %>% 
  set_names(colnames(x_seen)) %>% 
  select(contains('ANA'), contains('SMI'),contains('SCI'), contains('SRI')) %>% 
  mutate(iteration = 1:nrow(.)) %>% 
  gather(cluster_region, beta_hat,-iteration) %>% 
  tidyr::separate(cluster_region,c('cluster','region'),'-') %>% 
  group_by(cluster,region) %>% 
  mutate(cs_beta_hat = (beta_hat - mean(beta_hat)) / (2 * sd(beta_hat))) %>% ungroup()

a <- region_betas %>% 
  filter(region == 'SMI', cluster == 1) %>% 
  select(-cs_beta_hat) %>% 
  mutate(lag2_beta = lag(beta_hat))


```


```{r}

selectInput(
      'regions',
      'Regions to plot' ,
      choices = unique(region_betas$region),
      multiple = T,
      selectize = T
    )


```

```{r}

selectInput(
      'clusters',
      'Clusters to plot' ,
      choices = unique(region_betas$cluster),
      multiple = T,
      selectize = T
    )


```


make plots

```{r}

renderPlot({
  
  out <- region_betas %>% 
    filter(region %in% input$regions,
           cluster %in% input$clusters) %>% 
    ggplot(aes(iteration, cs_beta_hat, color = region)) + 
    geom_line(alpha = 0.5) +
  facet_wrap(~cluster) +
  theme_classic() + 
  viridis::scale_color_viridis(discrete = T)
  
  out
  
})



```






