---
title: "Ahnold Lit Review"
output: html_notebook
biblio-style: apalike
bibliography: Dissertation.bib
---

Literature review for project ahnold

## @Fletcher2015

Abstract: A rare opportunity to test hypotheses about potential fishery benefits of large- scale closures was initiated in July 2004 when an additional 28.4% of the 348 000 km2 Great Barrier Reef (GBR) region of Queensland, Australia was closed to all fishing. Advice to the Australian and Queensland governments that supported this initiative predicted these additional closures would generate minimal (10%) initial reductions in both catch and landed value within the GBR area, with recovery of catches becoming apparent after three years. To test these predictions, commercial fisheries data from the GBR area and from the two adjacent (non-GBR) areas of Queensland were compared for the periods immediately before and after the closures were implemented.
The observed means for total annual catch and value within the GBR declined from pre- closure (2000–2003) levels of 12780 Mg and Australian $160 million, to initial post-closure (2005–2008) levels of 8143 Mg and $102 million; decreases of 35% and 36% respectively. Because the reference areas in the non-GBR had minimal changes in catch and value, the beyond-BACI (before, after, control, impact) analyses estimated initial net reductions within the GBR of 35% for both total catch and value. There was no evidence of recovery in total catch levels or any comparative improvement in catch rates within the GBR nine years after implementation. These results are not consistent with the advice to governments that the closures would have minimal initial impacts and rapidly generate benefits to fisheries in the GBR through increased juvenile recruitment and adult spillovers. Instead, the absence of evidence of recovery in catches to date currently supports an alternative hypothesis that where there is already effective fisheries management, the closing of areas to all fishing will generate reductions in overall catches similar to the percentage of the fished area that is closed.

  * Control are two regions adjacent to GBR, not GBR itself
  *  35-36% decreases in catch and revenues
  * Reference areas had minimal changes in catch and value, so per BACI analysis all changes in value attributed to GBR itself
  * 2004 increase from 4.6 to 33% of total area in no take fishing
  * Assumption is that "bracketing" regions are effective controls
    * Share common Queensland fisheries regulations
  * Assume that MPAs had no affect on adjacent areas: isn't it possible that more people moved into those areas?
  * Uh, isn't the fact that there was an effort buyback in 2004 in the GBR kind of a big deal? Did those not affect the "control" sites? Don't think so, it says GBR
  * Seems like there could be an issue where the coming GBR is increasing catch in the nonGBR up till 2004, see Fig.2

## @Hughes2016

  * Claim that effective fishing area lost was much lower, though don't really provide any evidence for this besides trawl data, where the biggest impact seems to have been on line fishing?
  * What the hell do Spanish mackerel have to do with GBR fishery status?
  * So they're missing federal data? Could definitely be a problem if you think that there's a differential impact
  * The BACI critique seems like the most reasonable to me, especially given the lack of coral trout, which presumably are part of the line fishery where the biggest impact is seen, aren't in the other areas
  * All in all, response seems more flawed than original piece

## @Hopf2016
  * Mediocre MSE comparison to data

## @Hamilton2010

  * Might need to think about creating bioregion effects, definitely included either as hierarchichal priors for the sites, or as interaction terms somewhere
  * You need to figure out why you're seeing such difference responses in density ratios from this paper
  * Look into mining paper for best species to consider
  * Porbably worth trying to recreate some things here to make sure that you're not just seeing an artifact 
  * Consider effects based on species types
  * "It remains to be seen whether the Channel Islands reserve network enhances fisheries through spillover and larval subsidy effects." booya
  * Definitely need to look into @Kellner2007
  

## References
